### ISSUE TITLE
Guzzle version conflict

### ISSUE THREAD

**Issue by UnifySoftTech** [renoki-co/laravel-web3#20]
Hi i was trying to install this in my Laravel 8 project but it gives a guzzle version error, as this package depends on guzzle 6 but Laravel 8 and most of the latest packages require guzzle 7.

It wil be very helpful if you can provide some solution.

Thanks

**Comment by UnifySoftTech** [comment]
@rennokki  if you can please look into this, thanks in advance.

**Comment by rennokki** [comment]
It seems like it's because `sc0vu/web3.php` enforces 6.0 for guzzle, so nothing I can do for now. 😨

**Comment by UnifySoftTech** [comment]
okay thanks for the quick response, i will look into raw JS library then.

**Comment by rennokki** [comment]
@UnifySoftTech Best I can do is to switch to PHP Web3 package: https://github.com/renoki-co/laravel-web3/pull/21

**Comment by UnifySoftTech** [comment]
well if this can be helpful
