### ISSUE TITLE
How open Metamask?

### ISSUE THREAD

**Issue by carlosalbertocruz** [renoki-co/laravel-web3#24]
How open the metamask in laravel?

**Comment by rennokki** [comment]
This package is a wrapper for [web3-php/web3](https://github.com/web3-php/web3), so all the questions regarding the usage should go to their issue board.

If you're asking how to integrate with MetaMask, check this MetaMask tutorial: https://docs.metamask.io/guide/create-dapp.html#basic-action-part-1
