### ISSUE TITLE
Please batch json rpc first.

### ISSUE THREAD

**Issue by asoltani927** [renoki-co/laravel-web3#6]
How can I fix this error?

```
RuntimeException
Please batch json rpc first.
```

Web3\Providers\HttpProvider::execute
vendor/sc0vu/web3.php/src/Providers/HttpProvider.php:91

     */

    public function execute($callback)

    {

        if (!$this->isBatch) {

            throw new \RuntimeException('Please batch json rpc first.');

        }

        $methods = $this->methods;

        $proxy = function ($err, $res) use ($methods, $callback) {

            if ($err !== null) {

                return call_user_func($callback, $err, null);

            }

**Comment by rennokki** [comment]
This package is just a wrapper/facade for the web3.php. Please post this issue here: https://github.com/web3p/web3.php
